### ISSUE TITLE
[LUIS] Continuous Queue for Training

### ISSUE THREAD

**Issue by megancooper** [Microsoft/Cognitive-LUIS-Windows#42]
I've been trying to train my luis application but every time I hit the train button it just says "Queued for training" continuously. Has microsoft found a fix for this bug?

**Comment by stahaquadri** [comment]
I am looking for the same solution

**Comment by megancooper** [comment]
The issue was on Microsoft's side I believe. Try sending a help request from the site and they should get back to you within 24 hours.

**Comment by Sakshams** [comment]
I am still seeing this issue using the rest apis

**Comment by vipulkelkar** [comment]
I am also experiencing this issue today. I created a new intent and a composite entity. Started training the bot and it is in a stuck state.

**Comment by tsuwandy** [comment]
I'm alerting the team, thank you for letting us know.

**Comment by tsuwandy** [comment]
Hi, this looks to be a UI bug on the portal.  Training actually completed successfully.   Train button is green and accessing app dashboard for the first time shows the last successful training time.  The UI will keep showing the message "Queued for training..." unfortunately, team is aware of this issue and working on a fix.  

Please let us know if you are seeing otherwise.   Thank you!

**Comment by tsuwandy** [comment]
Issue should be fixed now.  Please comment otherwise.

**Comment by vipulkelkar** [comment]
i still see this issue. Yesterday, I had to create a new LUIS app and train it. Training for that new app just worked fine. But the one for which I reported the issue still gets stuck whenever I start the training.

**Comment by HaneefCoder** [comment]
Please check your application training status.
https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/{app_id}/versions/1.0/train
Headers :-
Ocp-Apim-Subscription-Key : {}
